<?php
require_once __DIR__ . '/_bootstrap.php';
admin_require();
$id = (int)($_GET['id'] ?? 0);
$stmt=$mysqli->prepare('SELECT * FROM reward_items WHERE id=? LIMIT 1');
$stmt->bind_param('i',$id);
$stmt->execute();
$reward=$stmt->get_result()->fetch_assoc();
if(!$reward){die('Reward not found');}
?>
<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Edit Reward</title><style>body{font-family:Arial,sans-serif;padding:16px}input,textarea{width:100%;padding:10px;margin:6px 0;border:1px solid #ddd;border-radius:8px}button,a{padding:10px 12px;border:1px solid #111;border-radius:8px;background:#111;color:#fff;text-decoration:none}</style></head><body><h2>Edit Reward</h2><p><a href='rewards_list.php'>Back</a></p><style>body{font-family:Arial,sans-serif;padding:16px}input,textarea{width:100%;padding:10px;margin:6px 0;border:1px solid #ddd;border-radius:8px}button,a{padding:10px 12px;border:1px solid #111;border-radius:8px;background:#111;color:#fff;text-decoration:none}</style></head><body><h2>Edit Reward</h2><p><a href='rewards_list.php'>Back</a></p><form method='post' action='reward_update.php'><input type='hidden' name='id' value='<?php echo (int)$reward["id"]; ?>'><label>Title</label><input name='title' required value='<?php echo e($reward["title"]); ?>'><label>Description</label><textarea name='description' rows='4'><?php echo e($reward["description"] ?? ''); ?></textarea><label>Points Required</label><input type='number' min='1' name='points_required' required value='<?php echo (int)$reward["points_required"]; ?>'><label>Stock</label><input type='number' min='0' name='stock' value='<?php echo (int)$reward["stock"]; ?>'><label>Image Path</label><input name='image_path' value='<?php echo e($reward["image_path"] ?? ''); ?>'><p><button type='submit'>Update</button></p></form></body></html><h2>Edit Reward</h2><p><a href='rewards_list.php'>Back</a></p><form method='post' action='reward_update.php'><input type='hidden' name='id' value='<?php echo (int)$reward["id"]; ?>'><label>Title</label><input name='title' required value='<?php echo e($reward["title"]); ?>'><label>Description</label><textarea name='description' rows='4'><?php echo e($reward["description"] ?? ''); ?></textarea><label>Points Required</label><input type='number' min='1' name='points_required' value='<?php echo (int)$reward["points_required"]; ?>' required><label>Stock</label><input type='number' min='0' name='stock' value='<?php echo (int)$reward["stock"]; ?>'><label>Image Path</label><input name='image_path' value='<?php echo e($reward["image_path"]); ?>'><p><button type='submit'>Update</button></p></form></body></html><label>Points Required</label><input type='number' min='1' name='points_required' value='<?php echo (int)$reward["points_required"]; ?>' required><label>Stock</label><input type='number' min='0' name='stock' value='<?php echo (int)$reward["stock"]; ?>'><label>Image Path</label><input name='image_path' value='<?php echo e($reward["image_path"] ?? ''); ?>'><p><button type='submit'>Update</button></p></form></body></html>