deployment:
  tasks:
    - export DEPLOYPATH=/home/thebertg/public_html/

    - /bin/mkdir -p $DEPLOYPATH

    - /bin/cp -R * $DEPLOYPATH

    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.gitignore

    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;