<?php
declare(strict_types=1);
session_start();

/* ==================== CONFIG ==================== */
const BASE_DIR = '/home/thebertg/';
const USERNAME = 'nathan';
// ⚠️ Replace this with a proper hash generated by password_hash('your_password', PASSWORD_DEFAULT)
const PASSWORD_HASH = '$argon2id$v=19$m=19456,t=2,p=1$M2ZmYmI3MDM5NTA1MzNhMDlhZjI0ZWUyZDVlZDU4NzQ$omxLe2E0E6A/P41qQkM6O8uFfVtSmn8FJvQb74yeITo';

/* ==================== HELPERS ==================== */
function h($s): string {
    return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8');
}

function base_real(): string {
    $b = realpath(BASE_DIR);
    if (!$b) {
        die("Invalid BASE_DIR");
    }
    return rtrim($b, '/');
}

function safe_join($rel): string {
    $base = base_real();
    $rel = ltrim((string)$rel, '/');
    $full = realpath($base . '/' . $rel);
    if (!$full) {
        return $base . '/' . $rel;
    }
    if (strpos($full, $base) !== 0) {
        die("Access denied");
    }
    return $full;
}

function copyRecursive($src, $dst): void {
    if (is_dir($src)) {
        if (!is_dir($dst)) {
            mkdir($dst, 0777, true);
        }
        foreach (scandir($src) as $file) {
            if ($file === '.' || $file === '..') {
                continue;
            }
            copyRecursive("$src/$file", "$dst/$file");
        }
    } else {
        copy($src, $dst);
    }
}

/* ==================== AUTH ==================== */
if (!isset($_SESSION['user'])) {
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        if (
            ($_POST['username'] ?? '') === USERNAME &&
            password_verify($_POST['password'] ?? '', PASSWORD_HASH)
        ) {
            $_SESSION['user'] = USERNAME;
            header("Location: ?");
            exit;
        }
    }
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>FM Login</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-slate-900 min-h-screen flex items-center justify-center p-4">
        <div class="bg-white/10 backdrop-blur-md rounded-2xl shadow-2xl p-8 w-full max-w-md border border-white/20">
            <h2 class="text-3xl font-bold text-white text-center mb-6">FM Login</h2>
            <form method="post" class="space-y-4">
                <input type="text" name="username" placeholder="Username" class="w-full px-4 py-3 rounded-xl bg-white/20 border border-white/30 text-white">
                <input type="password" name="password" placeholder="Password" class="w-full px-4 py-3 rounded-xl bg-white/20 border border-white/30 text-white">
                <button class="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-xl">Login</button>
            </form>
        </div>
    </body>
    </html>
    <?php
    exit;
}

/* ================ PATH ================ */
$path = $_GET['p'] ?? '';
$cwd = safe_join($path);

/* ================ CREATE ================ */
if (isset($_POST['create_folder'])) {
    $name = trim($_POST['folder_name'] ?? '');
    if ($name !== '') {
        mkdir($cwd . '/' . $name);
    }
}
if (isset($_POST['create_file'])) {
    $name = trim($_POST['file_name'] ?? '');
    if ($name !== '') {
        file_put_contents($cwd . '/' . $name, '');
    }
}

/* ================ UPLOAD ================ */
if (isset($_POST['upload_files'])) {
    foreach ($_FILES['files']['tmp_name'] as $k => $tmp) {
        $name = basename($_FILES['files']['name'][$k]);
        move_uploaded_file($tmp, $cwd . '/' . $name);
    }
}

/* ================ RENAME ================ */
if (isset($_POST['rename_file'])) {
    $oldName = trim($_POST['old_name'] ?? '');
    $newName = trim($_POST['new_name'] ?? '');
    if ($oldName !== '' && $newName !== '') {
        $oldPath = $cwd . '/' . $oldName;
        $newPath = $cwd . '/' . basename($newName);
        if (!file_exists($oldPath)) {
            $_SESSION['move_error'] = 'Source not found.';
        } elseif (file_exists($newPath)) {
            $_SESSION['move_error'] = 'Destination already exists.';
        } elseif (!rename($oldPath, $newPath)) {
            $_SESSION['move_error'] = 'Rename failed.';
        } else {
            $_SESSION['move_success'] = "Renamed '$oldName' to '$newName'.";
        }
    }
    header("Location: ?p=" . urlencode($path));
    exit;
}

/* ================ DELETE ================ */
if (isset($_POST['delete_file'])) {
    $deleteName = trim($_POST['delete_name'] ?? '');
    if ($deleteName !== '') {
        $file = $cwd . '/' . $deleteName;
        if (is_dir($file)) {
            $iterator = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($file, FilesystemIterator::SKIP_DOTS),
                RecursiveIteratorIterator::CHILD_FIRST
            );
            foreach ($iterator as $f) {
                $f->isDir() ? rmdir($f->getRealPath()) : unlink($f->getRealPath());
            }
            rmdir($file);
        } else {
            unlink($file);
        }
    }
    header("Location: ?p=" . urlencode($path));
    exit;
}

/* ================ EXTRACT ZIP (with relative destination) ================ */
if (isset($_POST['extract_zip'])) {
    $zipName = basename($_POST['zip_name'] ?? '');
    $destPathInput = trim($_POST['extract_dest_path'] ?? '');
    
    if ($destPathInput === '') {
        // Empty: extract to folder named after ZIP in current directory
        $destFull = $cwd . '/' . pathinfo($zipName, PATHINFO_FILENAME);
    } elseif (str_starts_with($destPathInput, '/')) {
        // Starts with '/': treat as absolute path within BASE_DIR
        $destFull = safe_join(ltrim($destPathInput, '/'));
    } else {
        // Relative path: append to current directory
        $destFull = safe_join(($path ? $path . '/' : '') . $destPathInput);
    }
    
    $zipPath = $cwd . '/' . $zipName;
    
    if (!file_exists($zipPath) || !is_file($zipPath)) {
        $_SESSION['move_error'] = 'ZIP file not found.';
    } else {
        $zip = new ZipArchive();
        if ($zip->open($zipPath) === true) {
            if (!is_dir($destFull)) {
                if (!mkdir($destFull, 0777, true)) {
                    $_SESSION['move_error'] = 'Failed to create destination folder.';
                    header("Location: ?p=" . urlencode($path));
                    exit;
                }
            }
            if (!$zip->extractTo($destFull)) {
                $_SESSION['move_error'] = 'Extraction failed.';
            } else {
                $_SESSION['move_success'] = "ZIP extracted successfully to: " . $destFull;
            }
            $zip->close();
        } else {
            $_SESSION['move_error'] = 'Failed to open ZIP file.';
        }
    }
    header("Location: ?p=" . urlencode($path));
    exit;
}

/* ================ ZIP SELECTED ================ */
if (isset($_POST['zip_selected']) && !empty($_POST['selected'])) {
    $zipName = "archive_" . date("Ymd_His") . ".zip";
    $zipPath = sys_get_temp_dir() . "/" . $zipName;
    $zip = new ZipArchive();
    $zip->open($zipPath, ZipArchive::CREATE);
    foreach ($_POST['selected'] as $item) {
        $full = $cwd . '/' . $item;
        if (is_dir($full)) {
            $files = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($full, FilesystemIterator::SKIP_DOTS),
                RecursiveIteratorIterator::LEAVES_ONLY
            );
            foreach ($files as $file) {
                if (!$file->isDir()) {
                    $zip->addFile(
                        $file->getRealPath(),
                        substr($file->getRealPath(), strlen($cwd) + 1)
                    );
                }
            }
        } else {
            $zip->addFile($full, basename($full));
        }
    }
    $zip->close();
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . $zipName . '"');
    readfile($zipPath);
    unlink($zipPath);
    exit;
}

/* ================ MOVE SELECTED ================ */
if (isset($_POST['move_selected']) && isset($_POST['selected']) && isset($_POST['dest_path'])) {
    $destPath = trim($_POST['dest_path']);
    if ($destPath !== '') {
        $destFull = safe_join($destPath);
        if (!is_dir($destFull)) {
            $_SESSION['move_error'] = "Destination path invalid.";
        } else {
            $errors = [];
            $success = [];
            foreach ($_POST['selected'] as $item) {
                $source = $cwd . '/' . $item;
                $destItem = $destFull . '/' . basename($item);
                if (file_exists($destItem)) {
                    $errors[] = "'$item' exists.";
                    continue;
                }
                if (rename($source, $destItem)) {
                    $success[] = $item;
                } else {
                    $errors[] = "Failed '$item'";
                }
            }
            if ($success) {
                $_SESSION['move_success'] = "Moved: " . implode(', ', $success);
            }
            if ($errors) {
                $_SESSION['move_error'] = implode(' ', $errors);
            }
        }
    }
    header("Location: ?p=" . urlencode($path));
    exit;
}

/* ================ COPY SELECTED ================ */
if (isset($_POST['copy_selected']) && isset($_POST['selected']) && isset($_POST['copy_dest_path'])) {
    $destPath = trim($_POST['copy_dest_path']);
    if ($destPath !== '') {
        $destFull = safe_join($destPath);
        if (!is_dir($destFull)) {
            $_SESSION['move_error'] = "Copy destination invalid.";
        } else {
            $errors = [];
            $success = [];
            foreach ($_POST['selected'] as $item) {
                $source = $cwd . '/' . $item;
                $destItem = $destFull . '/' . basename($item);
                if (file_exists($destItem)) {
                    $errors[] = "'$item' exists.";
                    continue;
                }
                copyRecursive($source, $destItem);
                $success[] = $item;
            }
            if ($success) {
                $_SESSION['move_success'] = "Copied: " . implode(', ', $success);
            }
            if ($errors) {
                $_SESSION['move_error'] = implode(' ', $errors);
            }
        }
    }
    header("Location: ?p=" . urlencode($path));
    exit;
}

/* ================== EDITOR ================== */
if (isset($_GET['edit'])) {
    $editName = urldecode($_GET['edit']);
    $file = $cwd . '/' . $editName;

    if (isset($_POST['save'])) {
        if (!is_writable($file)) {
            chmod($file, 0644);
        }
        file_put_contents($file, $_POST['content'] ?? '');
    }

    $content = is_file($file) ? file_get_contents($file) : '';
    $extension = pathinfo($editName, PATHINFO_EXTENSION);
    $languageMap = [
        'php' => 'php',
        'js' => 'javascript',
        'html' => 'html',
        'css' => 'css',
        'json' => 'json',
        'py' => 'python',
        'md' => 'markdown',
        'txt' => 'text'
    ];
    $language = $languageMap[$extension] ?? 'text';
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <title>Editing: <?= h($editName) ?></title>
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs/loader.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
        <style>
            body { font-family: 'Inter', sans-serif; }
            .monaco-editor { position: absolute; top: 60px; bottom: 0; left: 0; right: 0; }
        </style>
    </head>
    <body class="bg-[#0f1115] text-white">
        <form method="post" id="editorForm" class="h-screen flex flex-col">
            <div class="bg-[#1e1f29] border-b border-gray-700 px-4 py-3 flex flex-wrap items-center justify-between gap-3 sticky top-0 z-10">
                <div class="flex items-center gap-3 flex-wrap">
                    <a href="?p=<?= h($path) ?>" class="inline-flex items-center gap-2 px-3 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg transition text-sm font-medium">← Back</a>
                    <div class="text-sm text-gray-300 bg-black/30 px-3 py-1.5 rounded-lg font-mono break-all">
                        <?= BASE_DIR . $path . '/' . $editName ?>
                    </div>
                </div>
                <div class="flex gap-2">
                    <button type="button" onclick="undoEditor()" class="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg text-sm">Undo</button>
                    <button type="button" onclick="redoEditor()" class="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg text-sm">Redo</button>
                    <button type="submit" name="save" class="px-5 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg text-sm shadow-lg">Save</button>
                </div>
            </div>
            <textarea id="mobileEditor" name="content" class="hidden w-full h-full bg-[#0b0f14] text-[#e6edf3] font-mono text-base p-4 resize-none focus:outline-none"></textarea>
            <div id="editor" class="flex-1"></div>
        </form>
        <script>
            const isMobile = /Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
            let editor;
            if (isMobile) {
                document.getElementById('mobileEditor').classList.remove('hidden');
                document.getElementById('mobileEditor').classList.add('block');
                document.getElementById('editor').style.display = 'none';
                document.getElementById('mobileEditor').value = <?= json_encode($content) ?>;
            } else {
                require.config({ paths: { vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs' } });
                require(['vs/editor/editor.main'], function() {
                    editor = monaco.editor.create(document.getElementById('editor'), {
                        value: <?= json_encode($content) ?>,
                        language: "<?= $language ?>",
                        theme: "vs-dark",
                        automaticLayout: true,
                        minimap: { enabled: false },
                        fontSize: 14,
                        lineNumbers: 'on',
                        scrollBeyondLastLine: false
                    });
                });
            }
            function saveContent() {
                if (editor) {
                    document.getElementById('mobileEditor').value = editor.getValue();
                }
            }
            function undoEditor() {
                if (editor) {
                    editor.trigger('', 'undo', null);
                } else {
                    document.getElementById('mobileEditor').focus();
                    document.execCommand('undo');
                }
            }
            function redoEditor() {
                if (editor) {
                    editor.trigger('', 'redo', null);
                } else {
                    document.getElementById('mobileEditor').focus();
                    document.execCommand('redo');
                }
            }
            document.getElementById('editorForm').addEventListener('submit', saveContent);
        </script>
    </body>
    </html>
    <?php
    exit;
}

/* ======================== LIST ======================== */
$scan = scandir($cwd);
$folders = [];
$files = [];
foreach ($scan as $item) {
    if ($item === '.' || $item === '..') {
        continue;
    }
    if (is_dir($cwd . '/' . $item)) {
        $folders[] = $item;
    } else {
        $files[] = $item;
    }
}
sort($folders);
sort($files);
$items = array_merge($folders, $files);
$parent = dirname($path);
if ($parent == '.') $parent = '';
$successMsg = $_SESSION['move_success'] ?? '';
$errorMsg = $_SESSION['move_error'] ?? '';
unset($_SESSION['move_success'], $_SESSION['move_error']);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modern File Manager</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Inter', sans-serif; }
        .card-hover { transition: all .2s ease; }
        .card-hover:hover { transform: translateY(-2px); box-shadow: 0 10px 25px -5px rgba(0,0,0,0.1); }
    </style>
</head>
<body class="bg-gradient-to-br from-slate-50 to-gray-100 min-h-screen">
    <div class="bg-white shadow-sm border-b border-gray-200 sticky top-0 z-20">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
            <div class="flex flex-wrap items-center justify-between gap-3">
                <div class="flex items-center gap-4">
                    <div class="flex items-center gap-2 text-2xl font-bold bg-gradient-to-r from-blue-700 to-indigo-600 bg-clip-text text-transparent">
                        <i class="fas fa-folder-open text-indigo-500"></i>
                        <span>FileManager</span>
                    </div>
                    <div class="hidden md:flex items-center gap-2 text-sm bg-gray-100 rounded-full px-4 py-2">
                        <i class="fas fa-location-dot text-gray-500"></i>
                        <span class="font-mono text-gray-700"><?= BASE_DIR . $path ?></span>
                    </div>
                </div>
                <div class="flex gap-2">
                    <a href="?p=<?= h($parent) ?>" class="inline-flex items-center gap-2 px-4 py-2 bg-gray-800 hover:bg-gray-900 text-white rounded-xl transition shadow-sm text-sm font-medium">
                        <i class="fas fa-arrow-left"></i> Back
                    </a>
                    <button onclick="window.location.reload()" class="px-4 py-2 border border-gray-300 rounded-xl hover:bg-gray-50 transition text-gray-700">
                        <i class="fas fa-sync-alt"></i>
                    </button>
                </div>
            </div>
            <div class="md:hidden mt-3 text-xs font-mono text-gray-500 bg-gray-50 p-2 rounded-lg break-all">
                <?= BASE_DIR . $path ?>
            </div>
        </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <?php if ($successMsg): ?>
            <div class="mb-4 bg-green-100 border-l-4 border-green-500 text-green-700 p-4 rounded-lg shadow-sm">
                <i class="fas fa-check-circle mr-2"></i> <?= h($successMsg) ?>
            </div>
        <?php endif; ?>
        <?php if ($errorMsg): ?>
            <div class="mb-4 bg-red-100 border-l-4 border-red-500 text-red-700 p-4 rounded-lg shadow-sm">
                <i class="fas fa-exclamation-circle mr-2"></i> <?= h($errorMsg) ?>
            </div>
        <?php endif; ?>

        <!-- Action Buttons -->
        <div class="flex flex-wrap gap-3 mb-6">
            <button onclick="openModal('createFolderModal')" class="flex items-center gap-2 bg-indigo-50 border border-indigo-200 rounded-xl p-3 hover:bg-indigo-100 transition">
                <i class="fas fa-folder-plus text-indigo-600 text-xl"></i>
                <span class="font-medium text-indigo-700">New Folder</span>
            </button>
            <button onclick="openModal('createFileModal')" class="flex items-center gap-2 bg-blue-50 border border-blue-200 rounded-xl p-3 hover:bg-blue-100 transition">
                <i class="fas fa-file-alt text-blue-600 text-xl"></i>
                <span class="font-medium text-blue-700">New File</span>
            </button>
            <button onclick="openModal('uploadModal')" class="flex items-center gap-2 bg-green-50 border border-green-200 rounded-xl p-3 hover:bg-green-100 transition">
                <i class="fas fa-upload text-green-600 text-xl"></i>
                <span class="font-medium text-green-700">Upload</span>
            </button>
            <button id="zipSelectedBtn" class="flex items-center gap-2 bg-purple-50 border border-purple-200 rounded-xl p-3 hover:bg-purple-100 transition">
                <i class="fas fa-file-archive text-purple-600 text-xl"></i>
                <span class="font-medium text-purple-700">Zip Selected</span>
            </button>
            <button onclick="openModal('moveModal')" class="flex items-center justify-center gap-2 bg-amber-50 border border-amber-200 rounded-xl p-3 hover:bg-amber-100 transition">
                <i class="fas fa-arrows-alt text-amber-600 text-xl"></i>
                <span class="font-medium text-amber-700">Move Selected</span>
            </button>
            <button onclick="openModal('copyModal')" class="flex items-center justify-center gap-2 bg-cyan-50 border border-cyan-200 rounded-xl p-3 hover:bg-cyan-100 transition">
                <i class="fas fa-copy text-cyan-600 text-xl"></i>
                <span class="font-medium text-cyan-700">Copy Selected</span>
            </button>
        </div>

        <form method="post" id="zipForm">
            <input type="hidden" name="zip_selected" value="1">
            <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-4 mb-4 flex flex-wrap items-center justify-between gap-3">
                <label class="inline-flex items-center gap-2 cursor-pointer">
                    <input type="checkbox" id="selectAllCheckbox" class="w-4 h-4 text-indigo-600 rounded border-gray-300 focus:ring-indigo-500">
                    <span class="text-sm font-medium text-gray-700"><i class="far fa-check-square"></i> Select All</span>
                </label>
                <span class="text-xs text-gray-500"><?= count($items) ?> item(s)</span>
            </div>
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">
                <?php foreach ($items as $i):
                    $isDir = is_dir($cwd . '/' . $i);
                    $isZip = (!$isDir && str_ends_with($i, '.zip'));
                    $icon = $isDir ? '<i class="fas fa-folder text-amber-500 text-2xl"></i>' : '<i class="fas fa-file text-slate-400 text-2xl"></i>';
                ?>
                <div class="bg-white rounded-xl shadow-sm border border-gray-100 card-hover overflow-hidden group">
                    <div class="p-4">
                        <div class="flex justify-between items-start">
                            <div class="flex items-center gap-2">
                                <input type="checkbox" name="selected[]" value="<?= h($i) ?>" class="item-checkbox w-4 h-4 text-indigo-600 rounded border-gray-300">
                                <?php if ($isDir): ?>
                                    <a href="?p=<?= urlencode(($path ? $path . '/' : '') . $i) ?>" class="hover:opacity-80">
                                        <i class="fas fa-folder text-amber-500 text-2xl hover:text-amber-600"></i>
                                    </a>
                                <?php else: ?>
                                    <?= $icon ?>
                                <?php endif; ?>
                            </div>
                            <div class="flex gap-1">
                                <?php if (!$isDir): ?>
                                    <a href="?p=<?= h($path) ?>&edit=<?= urlencode($i) ?>" target="_blank" class="p-1.5 text-gray-500 hover:text-blue-600"><i class="fas fa-pencil-alt"></i></a>
                                <?php endif; ?>
                                <button onclick="renameItem('<?= h($i) ?>')" class="p-1.5 text-gray-500 hover:text-green-600"><i class="fas fa-i-cursor"></i></button>
                                <button onclick="deleteItem('<?= h($i) ?>')" class="p-1.5 text-gray-500 hover:text-red-600"><i class="fas fa-trash"></i></button>
                                <?php if ($isZip): ?>
                                    <button onclick="extractZip('<?= h($i) ?>')" class="p-1.5 text-gray-500 hover:text-purple-600"><i class="fas fa-file-archive"></i></button>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="mt-2">
                            <?php if ($isDir): ?>
                                <a href="?p=<?= urlencode(($path ? $path . '/' : '') . $i) ?>" 
                                   class="block font-medium text-gray-800 truncate hover:text-indigo-600"
                                   title="<?= h($i) ?>">
                                    <?= h($i) ?>
                                </a>
                            <?php else: ?>
                                <div class="font-medium text-gray-800 truncate" title="<?= h($i) ?>">
                                    <?= h($i) ?>
                                </div>
                            <?php endif; ?>
                            <div class="text-xs text-gray-400 mt-1">
                                <?php if (!$isDir):
                                    $size = filesize($cwd . '/' . $i);
                                    $sizeStr = $size < 1024 ? $size . ' B' : ($size < 1048576 ? round($size/1024, 1) . ' KB' : round($size/1048576, 1) . ' MB');
                                ?>
                                    <i class="far fa-save"></i> <?= $sizeStr ?>
                                <?php else: ?>
                                    <i class="far fa-folder"></i> Folder
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
                <?php if (empty($items)): ?>
                    <div class="col-span-full text-center py-16 bg-white rounded-xl border border-dashed border-gray-300">
                        <i class="fas fa-folder-open text-5xl text-gray-300 mb-3"></i>
                        <p class="text-gray-500">This folder is empty</p>
                    </div>
                <?php endif; ?>
            </div>
        </form>
    </div>

    <!-- MODALS -->
    <!-- Create Folder Modal -->
    <div id="createFolderModal" class="fixed inset-0 bg-black/50 backdrop-blur-sm hidden items-center justify-center z-50 p-4" onclick="if(event.target === this) closeModal('createFolderModal')">
        <div class="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-xl font-bold text-gray-800"><i class="fas fa-folder-plus text-indigo-500 mr-2"></i>Create Folder</h3>
                <button onclick="closeModal('createFolderModal')" class="text-gray-400 hover:text-gray-600"><i class="fas fa-times"></i></button>
            </div>
            <form method="post">
                <input type="text" name="folder_name" placeholder="Folder name" class="w-full px-4 py-2 border border-gray-300 rounded-xl" required>
                <div class="mt-5 flex gap-3 justify-end">
                    <button type="button" onclick="closeModal('createFolderModal')" class="px-4 py-2 border border-gray-300 rounded-lg">Cancel</button>
                    <button type="submit" name="create_folder" class="px-4 py-2 bg-indigo-600 text-white rounded-lg">Create</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Create File Modal -->
    <div id="createFileModal" class="fixed inset-0 bg-black/50 backdrop-blur-sm hidden items-center justify-center z-50 p-4" onclick="if(event.target === this) closeModal('createFileModal')">
        <div class="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-xl font-bold text-gray-800"><i class="fas fa-file-alt text-blue-500 mr-2"></i>Create File</h3>
                <button onclick="closeModal('createFileModal')" class="text-gray-400 hover:text-gray-600"><i class="fas fa-times"></i></button>
            </div>
            <form method="post">
                <input type="text" name="file_name" placeholder="File name" class="w-full px-4 py-2 border border-gray-300 rounded-xl" required>
                <div class="mt-5 flex gap-3 justify-end">
                    <button type="button" onclick="closeModal('createFileModal')" class="px-4 py-2 border border-gray-300 rounded-lg">Cancel</button>
                    <button type="submit" name="create_file" class="px-4 py-2 bg-blue-600 text-white rounded-lg">Create</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Upload Modal -->
    <div id="uploadModal" class="fixed inset-0 bg-black/50 backdrop-blur-sm hidden items-center justify-center z-50 p-4" onclick="if(event.target === this) closeModal('uploadModal')">
        <div class="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-xl font-bold text-gray-800"><i class="fas fa-upload text-green-500 mr-2"></i>Upload Files</h3>
                <button onclick="closeModal('uploadModal')" class="text-gray-400 hover:text-gray-600"><i class="fas fa-times"></i></button>
            </div>
            <form method="post" enctype="multipart/form-data">
                <input type="file" name="files[]" multiple class="w-full border border-gray-300 rounded-xl p-2" required>
                <div class="mt-5 flex gap-3 justify-end">
                    <button type="button" onclick="closeModal('uploadModal')" class="px-4 py-2 border border-gray-300 rounded-lg">Cancel</button>
                    <button type="submit" name="upload_files" class="px-4 py-2 bg-green-600 text-white rounded-lg">Upload</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Move Modal -->
    <div id="moveModal" class="fixed inset-0 bg-black/50 backdrop-blur-sm hidden items-center justify-center z-50 p-4" onclick="if(event.target === this) closeModal('moveModal')">
        <div class="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-xl font-bold text-gray-800"><i class="fas fa-arrows-alt text-amber-500 mr-2"></i>Move Selected Items</h3>
                <button onclick="closeModal('moveModal')" class="text-gray-400 hover:text-gray-600"><i class="fas fa-times"></i></button>
            </div>
            <form method="post" id="moveForm">
                <input type="hidden" name="move_selected" value="1">
                <input type="text" name="dest_path" placeholder="Destination path" class="w-full px-4 py-2 border border-gray-300 rounded-xl" required>
                <div class="mt-5 flex gap-3 justify-end">
                    <button type="button" onclick="closeModal('moveModal')" class="px-4 py-2 border border-gray-300 rounded-lg">Cancel</button>
                    <button type="submit" class="px-4 py-2 bg-amber-600 text-white rounded-lg">Move</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Copy Modal -->
    <div id="copyModal" class="fixed inset-0 bg-black/50 backdrop-blur-sm hidden items-center justify-center z-50 p-4" onclick="if(event.target === this) closeModal('copyModal')">
        <div class="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-xl font-bold text-gray-800"><i class="fas fa-copy text-cyan-500 mr-2"></i>Copy Selected Items</h3>
                <button onclick="closeModal('copyModal')" class="text-gray-400 hover:text-gray-600"><i class="fas fa-times"></i></button>
            </div>
            <form method="post" id="copyForm">
                <input type="hidden" name="copy_selected" value="1">
                <input type="text" name="copy_dest_path" placeholder="Destination path" class="w-full px-4 py-2 border border-gray-300 rounded-xl" required>
                <div class="mt-5 flex gap-3 justify-end">
                    <button type="button" onclick="closeModal('copyModal')" class="px-4 py-2 border border-gray-300 rounded-lg">Cancel</button>
                    <button type="submit" class="px-4 py-2 bg-cyan-600 text-white rounded-lg">Copy</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Hidden Forms -->
    <form method="post" id="renameForm" class="hidden">
        <input type="hidden" name="rename_file" value="1">
        <input type="hidden" name="old_name" id="rename_old">
        <input type="hidden" name="new_name" id="rename_new">
    </form>
    <form method="post" id="deleteForm" class="hidden">
        <input type="hidden" name="delete_file" value="1">
        <input type="hidden" name="delete_name" id="delete_name_input">
    </form>
    <form method="post" id="extractForm" class="hidden">
        <input type="hidden" name="extract_zip" value="1">
        <input type="hidden" name="zip_name" id="extract_zip_name">
        <input type="hidden" name="extract_dest_path" id="extract_dest_path">
    </form>

    <script>
        function openModal(id) {
            document.getElementById(id).classList.remove('hidden');
            document.getElementById(id).classList.add('flex');
        }
        function closeModal(id) {
            document.getElementById(id).classList.add('hidden');
            document.getElementById(id).classList.remove('flex');
        }
        function renameItem(name) {
            let newName = prompt("Rename:", name);
            if (newName && newName !== name) {
                document.getElementById('rename_old').value = name;
                document.getElementById('rename_new').value = newName;
                document.getElementById('renameForm').submit();
            }
        }
        function deleteItem(name) {
            if (confirm('Delete "' + name + '"?')) {
                document.getElementById('delete_name_input').value = name;
                document.getElementById('deleteForm').submit();
            }
        }
        function extractZip(name) {
            let defaultDest = "<?= addslashes($path) ?>";
            let destPath = prompt("Extract \"" + name + "\" to folder:", defaultDest);
            if (destPath !== null) {
                document.getElementById('extract_zip_name').value = name;
                document.getElementById('extract_dest_path').value = destPath;
                document.getElementById('extractForm').submit();
            }
        }
        const selectAllCheckbox = document.getElementById('selectAllCheckbox');
        const itemCheckboxes = document.querySelectorAll('.item-checkbox');
        if (selectAllCheckbox) {
            selectAllCheckbox.addEventListener('change', function(e) {
                itemCheckboxes.forEach(cb => cb.checked = e.target.checked);
            });
        }
        document.getElementById('zipSelectedBtn').addEventListener('click', function() {
            let anyChecked = Array.from(itemCheckboxes).some(cb => cb.checked);
            if (!anyChecked) {
                alert('Select items first');
                return;
            }
            document.getElementById('zipForm').submit();
        });
        function injectSelected(formId) {
            const form = document.getElementById(formId);
            form.querySelectorAll('input[name="selected[]"]').forEach(e => e.remove());
            let checked = document.querySelectorAll('.item-checkbox:checked');
            if (checked.length === 0) {
                alert('Please select at least one item.');
                return false;
            }
            checked.forEach(cb => {
                let input = document.createElement('input');
                input.type = 'hidden';
                input.name = 'selected[]';
                input.value = cb.value;
                form.appendChild(input);
            });
            return true;
        }
        document.getElementById('moveForm').addEventListener('submit', function(e) {
            if (!injectSelected('moveForm')) e.preventDefault();
        });
        document.getElementById('copyForm').addEventListener('submit', function(e) {
            if (!injectSelected('copyForm')) e.preventDefault();
        });
    </script>
</body>
</html>