#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MASTER_CSS = ROOT / "docs" / "master.css"
MASTER_MIN_CSS = ROOT / "docs" / "master.min.css"
REPORT = ROOT / "docs" / "master-css-report.md"

SKIP_PATTERNS = (
    "ajax",
    "update",
    "delete",
    "toggle",
    "process",
    "config",
    "auth",
    "helpers",
    "_",
)

link_re = re.compile(r"<link[^>]*rel=[\"']?stylesheet[\"']?[^>]*>", re.IGNORECASE)
href_re = re.compile(r"href=[\"']([^\"']+)[\"']", re.IGNORECASE)
style_re = re.compile(r"<style[^>]*>(.*?)</style>", re.IGNORECASE | re.DOTALL)
comment_re = re.compile(r"/\*.*?\*/", re.DOTALL)
ws_re = re.compile(r"\s+")
php_re = re.compile(r"<\?(?:php|=)?.*?\?>", re.DOTALL | re.IGNORECASE)
html_tag_re = re.compile(r"<[^>]+>")


def is_likely_page(path: Path) -> bool:
    name = path.name.lower()
    if name in {"header.php", "footer.php", "functions.php", "init.php", "mobile-bottom-menu.php"}:
        return False
    if any(tok in name for tok in SKIP_PATTERNS):
        return False
    text = path.read_text(encoding="utf-8", errors="ignore").lower()
    return any(tag in text for tag in ("<html", "<!doctype", "<body", "<main", "<section", "<style", "stylesheet"))


def sanitize_css(css: str) -> str:
    css = php_re.sub("", css)
    css = html_tag_re.sub("", css)
    return css


def minify_css(css: str) -> str:
    css = sanitize_css(css)
    css = comment_re.sub("", css)
    css = ws_re.sub(" ", css)
    for before, after in (
        (" {", "{"),
        ("{ ", "{"),
        (" }", "}"),
        ("} ", "}"),
        ("; ", ";"),
        (": ", ":"),
        (" :", ":"),
        (", ", ","),
    ):
        css = css.replace(before, after)
    css = css.replace(";}", "}")
    return css.strip()


def extract_stylesheet_hrefs(text: str) -> list[str]:
    hrefs: list[str] = []
    for tag in link_re.findall(text):
        match = href_re.search(tag)
        if match:
            hrefs.append(match.group(1).strip())
    return hrefs


def resolve_local_css(page: Path, href: str) -> Path | None:
    cleaned = href.split("?", 1)[0].split("#", 1)[0]
    if cleaned.startswith(("http://", "https://", "//")):
        return None

    candidates: list[Path] = []
    if cleaned.startswith("/"):
        candidates.append(ROOT / cleaned.lstrip("/"))
    else:
        candidates.append((page.parent / cleaned).resolve())
        candidates.append(ROOT / cleaned)

    for candidate in candidates:
        if candidate.exists() and candidate.suffix == ".css":
            return candidate
    return None


def main() -> None:
    pages = sorted([p for p in ROOT.rglob("*.php") if ".git" not in p.parts and is_likely_page(p)])
    if not pages:
        raise SystemExit("No likely page files found")

    kept_chunks: list[tuple[str, str]] = []
    seen_chunks: set[str] = set()

    total_source_bytes = 0
    resolved_links = 0
    unresolved_links = 0
    inline_blocks = 0

    for page in pages:
        rel_page = page.relative_to(ROOT)
        text = page.read_text(encoding="utf-8", errors="ignore")

        for href in extract_stylesheet_hrefs(text):
            css_file = resolve_local_css(page, href)
            if not css_file:
                unresolved_links += 1
                continue
            resolved_links += 1
            css_text = css_file.read_text(encoding="utf-8", errors="ignore")
            total_source_bytes += len(css_text.encode("utf-8"))
            minified = minify_css(css_text)
            if minified and minified not in seen_chunks:
                seen_chunks.add(minified)
                kept_chunks.append((f"{rel_page} -> {css_file.relative_to(ROOT)}", minified))

        for idx, block in enumerate(style_re.findall(text), start=1):
            inline_blocks += 1
            total_source_bytes += len(block.encode("utf-8"))
            minified = minify_css(block)
            if minified and minified not in seen_chunks:
                seen_chunks.add(minified)
                kept_chunks.append((f"{rel_page} inline#{idx}", minified))

    master_parts = ["/* Master CSS generated by scripts/build_master_css.py */"]
    for source, chunk in kept_chunks:
        master_parts.append(f"\n/* {source} */")
        master_parts.append(chunk)

    master_text = "\n".join(master_parts).strip() + "\n"
    MASTER_CSS.write_text(master_text, encoding="utf-8")

    master_min = minify_css(master_text) + "\n"
    MASTER_MIN_CSS.write_text(master_min, encoding="utf-8")

    report_lines = [
        "# Master CSS Build Report",
        "",
        f"- Pages scanned: {len(pages)}",
        f"- Resolved linked stylesheets: {resolved_links}",
        f"- Unresolved linked stylesheets: {unresolved_links}",
        f"- Inline style blocks: {inline_blocks}",
        f"- Unique CSS chunks kept: {len(kept_chunks)}",
        f"- Total source bytes read: {total_source_bytes}",
        f"- `docs/master.css` bytes: {len(master_text.encode('utf-8'))}",
        f"- `docs/master.min.css` bytes: {len(master_min.encode('utf-8'))}",
        "",
        "## Sources included",
    ]
    report_lines.extend(f"- `{source}`" for source, _ in kept_chunks)
    REPORT.write_text("\n".join(report_lines) + "\n", encoding="utf-8")

    print("Wrote docs/master.css, docs/master.min.css, docs/master-css-report.md")


if __name__ == "__main__":
    main()
